### ISSUE TITLE
Possible typo in an example code

### ISSUE THREAD

**Issue by i-rinat** [google/kunit-docs#1]
You probably wanted to name function parameter `parent`, instead of `this`. Otherwise there will be a compilation error.

https://github.com/google/kunit-docs/blob/dda544a5770ab27704bb59a95b19690d4ec4e366/third_party/kernel/docs/_sources/usage.rst.txt#L341-L344

**Comment by bjh83** [comment]
Nice catch! Sorry, I didn't see your comment earlier (we use this repo just for hosting website content).

**Comment by bjh83** [comment]
I just referenced this in our bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=205257
